artifacts_root: src/Recommendation/boardgame_recommendation_system/artifacts

data_deploy:
  root_dir: src/Recommendation/boardgame_recommendation_system/artifacts/data_deploy
  weight_ratings_hb_file: src/Hybrid_RS/boardgame_recommendation_system/artifacts/data_preparing/weight_ratings_hb_preparing.csv
  bg_info : src/Hybrid_RS/boardgame_recommendation_system/artifacts/data_ingestion/games_detailed_info.csv
  data_cb: src/Content_Based_RS/boardgame_recommendation_system/artifacts/pickle_folder/knowledge_stems_cb.pkl
  similarity_cb: src/Content_Based_RS/boardgame_recommendation_system/artifacts/pickle_folder/similarity_cb.pkl
  model_cfb: src/Collaborative_Filtering_Based_RS/boardgame_recommendation_system/artifacts/pickle_folder/model_cfb.pkl
  bg_pivot_cfb: src/Collaborative_Filtering_Based_RS/boardgame_recommendation_system/artifacts/pickle_folder/bg_pivot_cfb_processing.pkl
  dir_deploy: app/artifacts
  file_zip: app/artifacts/data.zip
  zip_dir: src/Recommendation/boardgame_recommendation_system/artifacts/zipfile
  all_file_cfb: src/Collaborative_Filtering_Based_RS/boardgame_recommendation_system/artifacts
  all_file_cb: src/Content_Based_RS/boardgame_recommendation_system/artifacts

