version: '3.9'

services:
  app-bg-recsys:
    image: app-bg-recsys
    build: 
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app/app.py
      FLASK_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/mydatabase

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: